### ISSUE TITLE
First Letter Spacing issue

### ISSUE THREAD

**Issue by nitras** [itsnwa/darkfolio#2]
Hi, 
The moment you edit the header file, it will create an odd spacing behind the first letter.

My workflow was:

1/ Clone the darkfolio project
2/ Edit say hi! to : contact

And you immediately see the space between D Ark P ortfolio when you hover.
Obviously the issue is not there when you disable the effect in the data/theme.json

In other tests, I have not touched the actual inner content of the header, but added an H1 or logo. Then there is no issue. The moment you edit contact to something else, there's this odd gap between the first letter. It's irreversible.

I kindly request how to fix this as inspecting the elements doesn't lead me anywhere.

**Comment by itsnwa** [comment]
Oh, interesting! I'll take a look. Thanks for letting me know 👍

**Comment by itsnwa** [comment]
@nitras It's working as expected when I test in Safari, Chrome and Firefox.

**Comment by nitras** [comment]
@itsnwa No worries, the strange thing is, it does happen here. And even more bizar was, it wasn't inspectable through dev tools (I just saw the space but there was no added padding, margin, or even actual space in the html. I ended up recreating the effect without the text splitting code. Aka simply doing css.

I'll try again one day and see how that goes. Thanks for responding!

**Comment by itsnwa** [comment]
@nitras cool, I will close this issue for now then. Might look into other solutions later.
